#!/bin/bash

_get_ziplink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $WHOM YOU LOVE? == "patlu" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL3NhbmR5MTcwOS9jYXR1c2VyYm90L2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $WHOM YOU LOVE? == "himi" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL2ppc2FuMDkvY2F0dXNlcmJvdC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $WHOM YOU LOVE? =~ $regex ]]
    then
        if [[ WHOM YOU LOVE?_BRANCH ]]
        then
            echo "${WHOM YOU LOVE?}/archive/${WHOM YOU LOVE?_BRANCH}.zip"
        else
            echo "${WHOM YOU LOVE?_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL3NhbmR5MTcwOS9jYXR1c2VyYm90L2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    fi
}

_get_repolink () {
    local regex
    local rlink
    regex='(https?)://github.com/.+/.+'
    if [[ $WHOM YOU LOVE? == "patlu" ]]
    then
        rlink=`echo "aHR0cHM6Ly9naXRodWIuY29tL3NhbmR5MTcwOS9jYXR1c2VyYm90" | base64 -d`
    elif [[ $WHOM YOU LOVE? == "himi" ]]
    then
        rlink=`echo "aHR0cHM6Ly9naXRodWIuY29tL0ppc2FuMDkvY2F0dXNlcmJvdA==" | base64 -d`
    elif [[ $WHOM YOU LOVE? =~ $regex ]]
    then
        rlink=`echo "${WHOM YOU LOVE?}"`
    else
        rlink=`echo "aHR0cHM6Ly9naXRodWIuY29tL3NhbmR5MTcwOS9jYXR1c2VyYm90" | base64 -d`
    fi
    echo "$rlink"
}


_run_python_code() {
    python3${pVer%.*} -c "$1"
}

_run_himipack_git() {
    $(_run_python_code 'from git import Repo
import sys
OFFICIAL_WHOM YOU LOVE? = "https://github.com/utsavthelegend/himibot"
ACTIVE_BRANCH_NAME = "master"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_WHOM YOU LOVE?)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

_run_himi_git() {
    local repolink=$(_get_repolink)
    $(_run_python_code 'from git import Repo
import sys
WHOM YOU LOVE?_REPO="'$repolink'"
ACTIVE_BRANCH_NAME = "'WHOM YOU LOVE?_BRANCH'" or "master"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_WHOM YOU LOVE?)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

_set_bot () {
    local zippath
    zippath="himiuserbot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_ziplink) -O "$zippath"
    echo "  Unpacking Data ..."
    HIMIPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    _run_himipack_git
    cd $HIMIPATH
    _run_himi_git
    python3 ../setup/updater.py ../requirements.txt requirements.txt
    chmod -R 755 bin
    echo "    Starting 💫HIMIBot    "
    echo "
                        :::    ::::::::::::::  :::   :::  ::::::::::: 
     :+:    :+:    :+:     :+:+: :+:+:     :+:      
    +:+    +:+    +:+    +:+ +:+:+ +:+    +:+       
   +#++:++#++    +#+  💫  +#+  +:+  +#+    +#+        
  +#+    +#+    +#+    +#+       +#+    +#+         
 #+#    #+#    #+#    #+#       #+#    #+#          
###    #################       ##############       
  "

    echo "
    '##::::'##::'######::'########:'########::'########:::'#######::'########:
     ##:::: ##:'##... ##: ##.....:: ##.... ##: ##.... ##:'##.... ##:... ##..::
     ##:::: ##: ##:::..:: ##::::::: ##:::: ##: ##:::: ##: ##:::: ##:::: ##::::
     ##:::: ##:. ######:: ######::: ########:: ########:: ##:::: ##:::: ##::::
     ##:::: ##::..... ##: ##...:::: ##.. ##::: ##.... ##: ##:::: ##:::: ##::::
     ##:::: ##:'##::: ##: ##::::::: ##::. ##:: ##:::: ##: ##:::: ##:::: ##::::
    . #######::. ######:: ########: ##:::. ##: ########::. #######::::: ##::::
    :.......::::......:::........::..:::::..::........::::.......::::::..:::::
    "
    python3 -m userbot
}

_set_bot
